version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  postgreSQL:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/

    env_file:
      - ../.env 

  django:
    build: ../backend/foodgram
    restart: always
    volumes:
      - static_value_django:/app/django_static/
      - media_value:/app/media/ 
    depends_on:
      - postgreSQL
    env_file:
      - ../.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value_django:/var/html/django_static/
      - media_value:/var/html/media/
    depends_on:
      - django

volumes:
  static_value_django:
  media_value: